# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Jiahao Cai Home Page
url:              http://jiahao-cai.info
paginate:         1
baseurl:          /
author:
  name:           Jiahao Cai
  url:            http://jiahao-cai.info
  email:          jc4mf@virginia.com

exclude: ["website.sublime-project", "website.sublime-workspace", "*.log", "*.fdb_latexmk", "*.synctex.gz", "*.aux", "cs7993"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: main
  -
    scope:
      path: "notebook"
      type: "posts"
    values:
      layout: "post"
      author: "Jiahao Cai"
  -
    scope:
      path: "etc"
      type: "pages"
    values:
      layout: "post"
      author: "Jiahao Cai"

kramdown:
  input: GFM

sass:
    sass_dir: _sass
    style: compressed

# Navigation
nav:
  - name:           "code"
    href:           "https://github.com/jiahao42"
    kind:           "dir"
  - name:           "posts"
    href:           "/posts"
    kind:           "dir"
  - name:           "etc"
    href:           "/etc"
    kind:           "dir"
  - name:           "paper"
    href:           "/paper"
    kind:           "dir"
  - name:           "about.txt"
    href:           "/"
    kind:           "file"

plugins:
  - jekyll-sitemap